name: mpox-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - streamlit>=1.24.0
  - numpy>=1.24.0
  - scipy>=1.10.0
  - matplotlib>=3.7.0
  - pillow>=9.5.0
  - pytest>=7.3.1
  - pytest-cov>=4.0.0
  - flake8>=6.0.0
  - pip>=23.0.0