name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up conda
      uses: conda-incubator/setup-miniconda@v3
      with:
        miniforge-variant: Mambaforge
        miniforge-version: latest
        activate-environment: mpox-env
        use-mamba: true
        python-version: '3.10'
        
    - name: Print environment info
      run: |
        conda info
        conda list
        pwd
        ls -la
        
    - name: Install dependencies
      run: |
        mamba env update -n mpox-env -f environment.yml
        pip install -e .
        
    - name: Run tests
      run: |
        python -m pytest tests/ -v
        
    - name: Lint with flake8
      run: |
        mamba install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics