name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up conda
      uses: conda-incubator/setup-miniconda@v3
      with:
        miniforge-variant: Miniforge3
        activate-environment: mpox-env
        environment-file: environment.yml
        python-version: '3.10'
        auto-activate-base: false
        use-only-tar-bz2: true
        
    - name: Print environment info
      run: |
        conda info
        conda list
        pwd
        ls -la
        
    - name: Install test dependencies
      run: |
        conda install pytest pytest-cov -y
        
    - name: Run tests
      run: |
        python -m pytest tests/ -v --import-mode=append
        
    - name: Lint with flake8
      run: |
        conda install flake8 -y
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics